### PR TITLE
add zip_url to response object

### PR DESCRIPTION
**Pull request by beatfreaker**

### CODE REVIEW

**Comment by zeke** [comment]
Hey @beatfreaker, sorry I missed this. Happy to roll it out.

Would you mind adding zip URL to the readme examples too?

**Comment by beatfreaker** [comment]
Hey @zeke added `zip_url` in readme too please check.

**Comment by zeke** [comment]
Thanks, @beatfreaker. Landed in 1.6.0

**Comment by beatfreaker** [comment]
Welcome, @zeke

**Pull request merged**
