### PR TITLE
fix: Support special characters in branch names

### PR DESCRIPTION
**Pull request by gordey4doronin**
* The most important fix is `branchMatch && branchMatch[0]`. Now it won't fail with an error (see below) if it's not able to parse the branch name.
* Fixed regex to work for single character branch names (use `*` instead of `+`)
* Fixed regex to allow `%` character (for URLs with escaped characters)
* Use newer node versions for CI

---

The error it used to fail when the branch regex has no matches:
```js
githubUrlToObject("https://github.com/gordey4doronin/test/tree/0")
Uncaught TypeError: Cannot read property '0' of null
```

---

Interesting observation. @zeke 
You had started fixing that problem back in 2019, but it seems never finished.
See this https://github.com/github-modules/github-url-to-object/compare/support-urls-with-encoded-branch-names

### CODE REVIEW

**Comment by zeke** [comment]
Thanks @gordey4doronin. Keep me posted as this progresses. Happy to ship when it's ready.

PS I'm open to switching from Travis to Actions here if it matters to y'all.

**Comment by gordey4doronin** [comment]
@zeke Done.
* The PR description updated.
* I didn't push `package-lock` file, I left it up to you to decide if you want to add it or not.
* I'm good to switch from Travis to Actions, but no strong opinion. And it's out of scope of this PR too.

**Comment by zeke** [comment]
```
Publish a new version of github-url-to-object (current: 4.0.5)

Commits:
- Merge pull request #40 from github-modules/gordey/special-characters  beb5400
- Remove very old node versions  8a014de
- Run on newer node versions  732df37
- Fix standard linting  fdcaded
- Actually build dist code  b917c70
- The actual fix  e0469dd
- Single character cases  dab8d56
- [WIP] fix: Special characters  fd73b86

Commit Range:
v4.0.5...master

Registry:
https://registry.npmjs.org/


  ✔ Prerequisite check
  ✔ Git
  ✔ Cleanup
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 github-url-to-object 4.0.6 published 🎉
```

**Comment by gordey4doronin** [comment]
Thank you!

**Pull request merged**
