### PR TITLE
Protect against falsy repository.url

### PR DESCRIPTION
**Pull request by revin**
In https://github.com/npm/marky-markdown/issues/386 we found a README (for [ember-runkit](https://www.npmjs.com/package/ember-runkit)) whose package.json contained `repository: {type: 'git', url: ''}`. Here's one way of handling that.

### CODE REVIEW

**Comment by revin** [comment]
Tests failed on node 0.10, looks like something in `standard` is broken on that version?

**Comment by zeke** [comment]
@revin I'm fine with dropping node 0.10 support here. Can you update the travis config?

**Comment by revin** [comment]
Done! All green ✅

**Comment by zeke** [comment]
Bumped the major to draw a line in the sand for dropped node 0.10 support. Versions are cheap!

```
❯ np major
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 github-url-to-object 4.0.0 published 🎉

**Comment by ashleygwilliams** [comment]
thanks so much @zeke !

**Pull request merged**
