### PR TITLE
add github enterprise support

### PR DESCRIPTION
**Pull request by dmathieu**

### CODE REVIEW

**Comment by zeke** [comment]
@dmathieu sorry I missed this. Fore some reason I wasn't getting notifications on this repo. Do you still want to try to land this?

**Comment by dmathieu** [comment]
We forked this to the heroku org: https://github.com/heroku/github-url-to-object
And are currently relying on that fork, which works fine.

I'm not working on this anymore. But @appleton or @gudmundur might want to weigh in.

**Comment by zeke** [comment]
@gudmundur, we meet again. :)

And hi, @appleton :)

Happy to help get this landed, but if you don't need it you don't need it.

**Comment by gudmundur** [comment]
Hi @zeke, we meet yet again!

We did a quick spike for GHE, not sure when we'll go further with that. I'm indifferent to be honest.

**Comment by zeke** [comment]
Okie doke. I'm tentatively closing this. Feel free to re-open if necessary.

**Pull request closed without merging**
