### PR TITLE
No node dependencies (util + url)

### PR DESCRIPTION
**Pull request by bfred-it**

### CODE REVIEW

**Comment by zeke** [comment]
Didn't know about `window.URL`. That's pretty cool.

I feel like dropping `format` makes this stuff harder to read. Does browserified `util` add much to the bundle size? If so, maybe https://github.com/knowledgecode/fast-format would be a good drop-in replacement.

**Comment by bfred-it** [comment]
I'd use ES6 template literals but then you'd need buble at least in the browserify step.

I'm thinking about bundling this in npmhub and anything that isn't a few lines is too much.

I can create a `String.replace`-based alternative in 2 lines if the current solution isn't unreadable

**Comment by zeke** [comment]
> buble

Haven't used that, but that would be fine with me. In general, another devDependency is okay with me if it can remove runtime dependencies and/or reduce the size of the browser bundle.

> anything that isn't a few lines is too much.

Why?

**Comment by bfred-it** [comment]
Because the Mozilla Addons reviewers will complain 😓 

But in general I agree that the less code the better

**Comment by zeke** [comment]
Let's do the `buble` thing with ES template strings.

**Comment by bfred-it** [comment]
Done. This might need a semver major since it drops 0.12 compat

**Comment by zeke** [comment]
> This might need a semver major since it drops 0.12 compat

Fine with me as 0.12 is EOL, but what change specifically breaks?

**Comment by bfred-it** [comment]
0.12 doesn't support temple literals

**Comment by zeke** [comment]
Oh obviously right.. Anyway to trick older node into using the browserified bundle? 🤔

**Comment by zeke** [comment]
We could just make the browser bundle the default export...

**Comment by bfred-it** [comment]
The browser bundle is not compatible with node because it uses window.URL

But yes we could use buble to transpile the node version without running it through browserify

**Comment by zeke** [comment]
How about we continue to use node's URL parser, transpile using buble, and have both node and browsers depend on the same dependency-free ES5 bundle?

**Comment by zeke** [comment]
0.10 is failing on Travis because it thinks the template strings are invalid.

The tests need to be pointed at the bundle too: https://github.com/zeke/github-url-to-object/blob/2e3e1aa1c22a34be691a22a3934b92b90fd39b01/test/index.js#L4

**Comment by zeke** [comment]
So.. no longer a breaking change right. Shall we call this a minor bump?

**Comment by bfred-it** [comment]
👍

**Comment by zeke** [comment]
```
❯ np minor
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 github-url-to-object 3.1.0 published 🎉
```

Thanks for your persistence, @bfred-it. 👍

**Pull request merged**
