### PR TITLE
add clone_url support

### PR DESCRIPTION
**Pull request by vladikoff**
cc @dannycoates

### CODE REVIEW

**Comment by zeke** [comment]
Hey sorry I missed this. What is clone URL for?

**Comment by vladikoff** [comment]
We use it here: https://github.com/dannycoates/able/blob/bb2f3fa147f9eaed790b5c0327cc3d7480ca13d0/project.js#L25

Basically if you provide a branch in the url:
```
  gh('github:monkey/business#nachos')
{
  user: 'monkey',
  repo: 'business',
  branch: 'nachos',
  https_url: 'https://github.com/monkey/business/tree/nachos',
  tarball_url: 'https://api.github.com/repos/monkey/business/tarball/nachos',
  travis_url: 'https://travis-ci.org/monkey/business',
  api_url: 'https://api.github.com/repos/monkey/business'
}
```
None of results above help you with cloning the repo with git.
i.e   https_url: 'https://github.com/monkey/business/tree/nachos', is not a valid clone url

**Comment by zeke** [comment]
I see. Would you mind adding this to the sample response in the README? If so, I'll happily merge this and publish a new version. Thanks!

**Comment by zeke** [comment]
@vladikoff it looks like this has some conflicts now. Are you still interested in landing it? If so, I'm happy to help get it out the door.

**Comment by vladikoff** [comment]
Updated, though there may be some styling issues because `master` is failing

**Comment by zeke** [comment]
Thanks @vladikoff! Landed in 2.1.0.

The tests were failing because `standard --format` was running on the /dist directory which is not `standard`-friendly javascript. That's fixed now: https://github.com/zeke/github-url-to-object/commit/fbd310b009cb7118cdef087fe58b080e2e38e066

The working demo has a new home at https://zeke.github.io/github-url-to-object

// @dannycoates

**Pull request merged**
